import Navbar from "@/components/ui/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col gap-8 bg-secondary min-h-screen">
      <Navbar />
      <div className="px-60">{children}</div>
    </div>
  );
}
